In [4]:
import pandas as pd
import numpy as np

In [2]:
ls

 Volume in drive D has no label.
 Volume Serial Number is A82D-86F7

 Directory of D:\Data_Analysis\Day3_Data_Preprocessing

12-03-2026  22:41    <DIR>          .
12-03-2026  22:40    <DIR>          ..
12-03-2026  22:41    <DIR>          .ipynb_checkpoints
12-03-2026  22:41               337 Learning_Preprocessing.ipynb
               1 File(s)            337 bytes
               3 Dir(s)  361,887,571,968 bytes free

In [3]:
ls

 Volume in drive D has no label.
 Volume Serial Number is A82D-86F7

 Directory of D:\Data_Analysis\Day3_Data_Preprocessing

12-03-2026  22:43    <DIR>          .
12-03-2026  22:40    <DIR>          ..
12-03-2026  22:41    <DIR>          .ipynb_checkpoints
12-03-2026  22:43    <DIR>          Google_Playstore
12-03-2026  22:41               337 Learning_Preprocessing.ipynb
               1 File(s)            337 bytes
               4 Dir(s)  361,884,876,800 bytes free

In [5]:
data = pd.read_csv("Google_Playstore/googleplaystore.csv")

In [7]:
data

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Price,Content Rating,Genres,Released,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",0,Everyone,Art & Design,"Aughust 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [10]:
data.isnull().sum()    #Everything is false beacuse no value NaN here

Unnamed: 0           0
App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Price                0
Content Rating       1
Genres               0
Released             0
Current Ver          8
Android Ver          3
dtype: int64

In [16]:
df = data.dropna()

In [15]:
df

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Price,Content Rating,Genres,Released,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",0,Everyone,Art & Design,"Aughust 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [18]:
df.isnull().sum()

Unnamed: 0        0
App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Price             0
Content Rating    0
Genres            0
Released          0
Current Ver       0
Android Ver       0
dtype: int64