In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
ls

 Volume in drive D has no label.
 Volume Serial Number is A82D-86F7

 Directory of D:\Data_Analysis\Day3_Data_Preprocessing

13-03-2026  20:47    <DIR>          .
13-03-2026  20:28    <DIR>          ..
13-03-2026  20:47    <DIR>          .ipynb_checkpoints
13-03-2026  17:01            27,835 1.Learning_Preprocessing.ipynb
13-03-2026  20:29            19,971 2.DataAnalysis_Numeric.ipynb
13-03-2026  20:29            36,927 3.NullValuesHandling.ipynb
13-03-2026  20:46               337 4.DataAnalysis_withConditions.ipynb
13-03-2026  18:00               218 Data.csv
13-03-2026  20:39    <DIR>          Google_Playstore
               5 File(s)         85,288 bytes
               4 Dir(s)  361,884,663,808 bytes free

In [3]:
df = pd.read_csv("Google_Playstore/googleplaystore.csv")

In [4]:
df = df.dropna()

In [5]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [11]:
df[df['Category'] == 'ART_AND_DESIGN']   #It will return those rows who have ART_AND_DESIGN category in the whole df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5258,AJ Styles Wallpaper 2018 - AJ Styles HD Wallpaper,ART_AND_DESIGN,4.0,18,3.6M,"1,000+",Free,0,Everyone,Art & Design,"March 22, 2018",1.1,4.0 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up
8679,Dp for girls,ART_AND_DESIGN,4.2,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.3,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

## Q1.How many free apps are there in ART_AND_DESIGN?

In [6]:
df_pr = df[df['Category'] == 'ART_AND_DESIGN']
print(len(df_pr[df_pr['Type'] == 'Free']))

58

## Q2.How many apps are there in ART_AND_DESIGN with rating more then 4.5?

In [10]:
df_pr = df[df['Category'] == 'ART_AND_DESIGN']
print(len(df_pr[df_pr['Rating'] > 4.5]))

22

## Q3.How many apps are there in FAMILY with rating more then 4.5 and Free?

In [8]:
df_pr = df[df['Category'] == 'FAMILY']
df_pr = df_pr[df_pr['Rating'] > 4.5]

len(df_pr[df_pr['Type'] == 'Free'])

314

## Q4.List all the free apps with rating more then 4.5 and category is FAMILY?

In [9]:
df_pr = df[df['Category'] == 'FAMILY']
df_pr = df_pr[df_pr['Rating'] > 4.5]

df_pr[df_pr['Type'] == 'Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2020,Super ABC! Learning games for kids! Preschool ...,FAMILY,4.6,20267,46M,"1,000,000+",Free,0,Everyone,Educational;Education,"July 16, 2018",1.1.6.7,4.1 and up
2023,Candy Pop Story,FAMILY,4.7,12948,23M,"1,000,000+",Free,0,Everyone,Casual;Brain Games,"May 24, 2018",2.0.3165,2.3 and up
2029,Dog Run - Pet Dog Simulator,FAMILY,4.7,48615,24M,"10,000,000+",Free,0,Everyone,Simulation;Action & Adventure,"May 22, 2018",1.4.12,4.1 and up
2032,Puzzle Kids - Animals Shapes and Jigsaw Puzzles,FAMILY,4.6,1109,52M,"1,000,000+",Free,0,Everyone,Educational;Brain Games,"July 18, 2018",1.0.6,4.1 and up
2040,"No. Color - Color by Number, Number Coloring",FAMILY,4.8,269194,6.9M,"10,000,000+",Free,0,Everyone,Entertainment;Brain Games,"August 3, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10691,Pin-fo,FAMILY,4.6,19,1.6M,500+,Free,0,Everyone,Entertainment,"August 15, 2016",3rd Release Aug 2016,2.2 and up
10801,Fr Ignacio Outreach,FAMILY,4.9,52,19M,"1,000+",Free,0,Everyone,Education,"January 19, 2018",1.0,4.4 and up
10809,Castle Clash: RPG War and Strategy FR,FAMILY,4.7,376223,24M,"1,000,000+",Free,0,Everyone,Strategy,"July 18, 2018",1.4.2,4.1 and up
10820,Fr. Daoud Lamei,FAMILY,5.0,22,8.6M,"1,000+",Free,0,Teen,Education,"June 27, 2018",3.8.0,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up