In [1]:
import pandas as pd
import numpy as np

In [4]:
s=pd.Series([1,2,3,4,5])
print("Original Series:")
display(s)

s_Squared = s.apply(lambda x: x**2)
print("\nSeries after applying lambda function(squaring):")
display(s_Squared)

Original Series:

0    1
1    2
2    3
3    4
4    5
dtype: int64

Series after applying lambda function(squaring):

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [8]:
s_Strings = pd.Series(['apple', 'banana', 'cherry'])
print("\nOriginal String Series:")
display(s_Strings)
s_UpperCase = s_Strings.apply(lambda x: x.upper())
print("\nSeries after applying lambda function(uppercase):")
display(s_UpperCase)

Original String Series:

0     apple
1    banana
2    cherry
dtype: object

Series after applying lambda function(uppercase):

0     APPLE
1    BANANA
2    CHERRY
dtype: object

In [12]:
data = {'col1': [10,20,30,40,50],
        'col2': ['A','B','C','D','E'],
        'col3': [100,200,150,250,300]}
df = pd.DataFrame(data)
display(df)
df['col1_transformed'] = df['col1'].apply(lambda x: x+5)
df['col2_transformed'] = df['col2'].apply(lambda x: f"ID_{x}")
print("\nDataFrame after applying lambda function to columns:")
display(df)

   col1 col2  col3
0    10    A   100
1    20    B   200
2    30    C   150
3    40    D   250
4    50    E   300

DataFrame after applying lambda function to columns:

   col1 col2  col3  col1_transformed col2_transformed
0    10    A   100                15             ID_A
1    20    B   200                25             ID_B
2    30    C   150                35             ID_C
3    40    D   250                45             ID_D
4    50    E   300                55             ID_E

In [14]:
#Lambda Function--> assign
#wWhenever we want to perform multiple operations and want new column out of it 

display(df)
df_assigned = df.assign(
    product_col1_col3 = lambda x: x['col1']*x['col3'],
    col1_isLarge = lambda x: x['col1']>30)
#Display the dataframe with the newly created columns
print("DataFrame after using assign with lambda:")
display(df_assigned)

   col1 col2  col3  col1_transformed col2_transformed
0    10    A   100                15             ID_A
1    20    B   200                25             ID_B
2    30    C   150                35             ID_C
3    40    D   250                45             ID_D
4    50    E   300                55             ID_E

DataFrame after using assign with lambda:

,col1,col2,col3,col1_transformed,col2_transformed,product_col1_col3,col1_isLarge
0,10,A,100,15,ID_A,1000,False
1,20,B,200,25,ID_B,4000,False
2,30,C,150,35,ID_C,4500,False
3,40,D,250,45,ID_D,10000,True
4,50,E,300,55,ID_E,15000,True

In [15]:
# 1. Create a sample DataFrame
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C', 'B', 'C'],
    'Value': [10, 15, 20, 25, 30, 35, 40, 45],
    'City': ['New York', 'London', 'New York', 'Paris', 'London', 'New York', 'Paris', 'London']
}
df_groupby = pd.DataFrame(data)

# 2. Print the original DataFrame
print("Original DataFrame:")
display(df_groupby)

# 3. Group by 'Category' and calculate the sum of 'Value'
print("\nGrouping by 'Category' and summing 'Value':")


category_sum = df_groupby.groupby('Category')['Value'].sum()
display(category_sum)

# 4. Group by multiple columns ('Category' and 'City') and calculate the mean of 'Value'

print("\nGrouping by 'Category' and 'City' and calculating the mean of 'Value':")

category_city_mean = df_groupby.groupby(['Category', 'City'])['Value'].mean()
display(category_city_mean)

Original DataFrame:

  Category  Value      City
0        A     10  New York
1        B     15    London
2        A     20  New York
3        B     25     Paris
4        A     30    London
5        C     35  New York
6        B     40     Paris
7        C     45    London

Grouping by 'Category' and summing 'Value':

Category
A    60
B    80
C    80
Name: Value, dtype: int64

Grouping by 'Category' and 'City' and calculating the mean of 'Value':

Category  City
A         London      30.0
          New York    15.0
B         London      15.0
          Paris       32.5
C         London      45.0
          New York    35.0
Name: Value, dtype: float64

In [17]:
# Group by 'Category'
display(df_groupby)
grouped_data = df_groupby.groupby('Category')

# 1. Apply agg() with built-in aggregation functions (mean and sum)
print("\nAggregating 'Value' by 'Category' using built-in functions (mean, sum):")
category_agg_builtin = grouped_data['Value'].agg(['mean', 'sum'])
display(category_agg_builtin)

# 2. Apply agg() with a lambda function for a custom aggregation (range: max - min)
print("\nAggregating 'Value' by 'Category' using a custom lambda function (range):")
category_agg_custom_lambda = grouped_data['Value'].agg(lambda x: x.max() - x.min())
category_agg_custom_lambda.name = 'Value_range' # Rename the series for clarity
display(category_agg_custom_lambda)

# 3. Demonstrate multiple custom aggregations using a dictionary
print("\nAggregating 'Value' by 'Category' using a dictionary with built-in and custom aggregations:")
category_multiple_agg = grouped_data['Value'].agg(
    mean_value='mean', # Built-in aggregation with custom name
    sum_value='sum',   # Built-in aggregation with custom name
    range_value=lambda x: x.max() - x.min(), # Custom aggregation with custom name
    count_elements='count' # Another built-in aggregation
)
display(category_multiple_agg)

  Category  Value      City
0        A     10  New York
1        B     15    London
2        A     20  New York
3        B     25     Paris
4        A     30    London
5        C     35  New York
6        B     40     Paris
7        C     45    London

Aggregating 'Value' by 'Category' using built-in functions (mean, sum):

               mean  sum
Category
A         20.000000   60
B         26.666667   80
C         40.000000   80

Aggregating 'Value' by 'Category' using a custom lambda function (range):

Category
A    20
B    25
C    10
Name: Value_range, dtype: int64

Aggregating 'Value' by 'Category' using a dictionary with built-in and custom aggregations:

          mean_value  sum_value  range_value  count_elements
Category
A          20.000000         60           20               3
B          26.666667         80           25               3
C          40.000000         80           10               2

In [18]:
# 1. Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Score': [85, 92, 78, 95, 88, 75],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney', 'Berlin']
}
df_sort = pd.DataFrame(data)

# 2. Print the original DataFrame
print("Original DataFrame:")
display(df_sort)

# 3. Create a new temporary column 'Name_Length' using a lambda function
df_sort['Name_Length'] = df_sort['Name'].apply(lambda x: len(x))
display(df_sort)


# 4. Sort the DataFrame by 'Name_Length' in ascending order
df_sorted_by_length = df_sort.sort_values(by='Name_Length', ascending=True)


# 5. Print the DataFrame sorted by the custom logic (name length)
print("\nDataFrame sorted by Name Length:")
display(df_sorted_by_length)

# 6. Optionally, drop the temporary 'Name_Length' column
df_sorted_by_length_cleaned = df_sorted_by_length.drop(columns=['Name_Length'])
print("\nDataFrame sorted by Name Length (without temporary column):")
display(df_sorted_by_length_cleaned)

Original DataFrame:

      Name  Score      City
0    Alice     85  New York
1      Bob     92    London
2  Charlie     78     Paris
3    David     95     Tokyo
4      Eve     88    Sydney
5    Frank     75    Berlin

      Name  Score      City  Name_Length
0    Alice     85  New York            5
1      Bob     92    London            3
2  Charlie     78     Paris            7
3    David     95     Tokyo            5
4      Eve     88    Sydney            3
5    Frank     75    Berlin            5

DataFrame sorted by Name Length:

      Name  Score      City  Name_Length
1      Bob     92    London            3
4      Eve     88    Sydney            3
0    Alice     85  New York            5
3    David     95     Tokyo            5
5    Frank     75    Berlin            5
2  Charlie     78     Paris            7

DataFrame sorted by Name Length (without temporary column):

      Name  Score      City
1      Bob     92    London
4      Eve     88    Sydney
0    Alice     85  New York
3    David     95     Tokyo
5    Frank     75    Berlin
2  Charlie     78     Paris

In [20]:
# DataFrame
data = {
    'Category': ['A','B','A','B','A','C','B','C'],
    'Value1': [10,15,np.nan,25,30,np.nan,40,45],
    'Value2': [100,np.nan,120,130,np.nan,150,160,170],
    'Aux_Value': [5,10,7,12,8,15,10,18]
}
df = pd.DataFrame(data)

print("Original:")
display(df)

# 1. Fill NaN for MULTIPLE columns using a dictionary
df_multiple = df.fillna({
    'Value1': df['Value1'].mean(),
    'Value2': df['Value2'].mean()
})

print("\nFill specific columns using a dictionary:")
display(df_multiple)

# 2. Fill EVERYTHING with a constant (global fill)
df_zero = df.fillna(0)

print("\nGlobal fillna(0):")
display(df_zero)

Original:

  Category  Value1  Value2  Aux_Value
0        A    10.0   100.0          5
1        B    15.0     NaN         10
2        A     NaN   120.0          7
3        B    25.0   130.0         12
4        A    30.0     NaN          8
5        C     NaN   150.0         15
6        B    40.0   160.0         10
7        C    45.0   170.0         18

Fill specific columns using a dictionary:

  Category  Value1      Value2  Aux_Value
0        A    10.0  100.000000          5
1        B    15.0  138.333333         10
2        A    27.5  120.000000          7
3        B    25.0  130.000000         12
4        A    30.0  138.333333          8
5        C    27.5  150.000000         15
6        B    40.0  160.000000         10
7        C    45.0  170.000000         18

Global fillna(0):

  Category  Value1  Value2  Aux_Value
0        A    10.0   100.0          5
1        B    15.0     0.0         10
2        A     0.0   120.0          7
3        B    25.0   130.0         12
4        A    30.0     0.0          8
5        C     0.0   150.0         15
6        B    40.0   160.0         10
7        C    45.0   170.0         18